services:
  samba:
    image: dockurr/samba
    container_name: ${SAMBA_SHARE_CONTAINER_NAME}
    network_mode: bridge
    environment:
      NAME: "${SAMBA_SHARE_NETWORK_NAME}"
      USER: "${SAMBA_SHARE_USER}"
      PASS: "${SAMBA_SHARE_PASS}"
      TZ: ${SAMBA_SHARE_TZ}
    ports:
      - 445:445
    volumes:
      - ${SAMBA_SHARE_PATH}:/storage
    restart: unless-stopped
