services:
  samba:
    image: dockurr/samba
    container_name: ${CONTAINER_NAME}
    network_mode: bridge
    environment:
      NAME: "${NETWORK_NAME}"
      USER: "${USER}"
      PASS: "${PASS}"
      TZ: America/Chicago
    ports:
      - 445:445
    volumes:
      - ${SHARE_PATH}:/storage
      - type: bind
        source: ${CONFIG_PATH}/${CONTAINER_NAME}/smb.conf
        target: /etc/samba/smb.conf
        read_only: true
    restart: unless-stopped
